import type { Metadata } from "next";
import { Inter, Urbanist } from "next/font/google";
import "./globals.css";
import ContextProvider from "./context/Context";

const inter = Inter({ subsets: ["latin"] });
const urbanist = Urbanist({
  subsets: ["latin"],
  style: ["normal"],
});

export const metadata: Metadata = {
  title: "ICON PERFOMANCE",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={urbanist.className}>
        <ContextProvider>{children}</ContextProvider>
      </body>
    </html>
  );
}
