export const RIOUTSTANDING_COLUMNS = [
  { name: "Claim No", dataIndex: "CM_NO" }, //
  { name: "Policy No", dataIndex: "CM_PL_NO" }, //
  { name: "Endorsement No", dataIndex: "CM_END_NO" }, //
  { name: "D.O.L", dataIndex: "CM_LOSS_DATE" }, //
  { name: "D.O.I", dataIndex: "CM_INT_DATE" }, //
  { name: "Registered On", dataIndex: "CREATED_ON" },
  { name: "Description", dataIndex: "CM_DESC" },
  { name: "Intermediary", dataIndex: "INTERMEDIARY" },
  { name: "Description Of Loss", dataIndex: "DESCRIPTION_OF_LOSS" },
  { name: "Managed As", dataIndex: "CM_MANAGED_AS" },
  { name: "Opened On", dataIndex: "CM_OPENED_ON" },
  { name: "From Date", dataIndex: "PL_FM_DT" },
  { name: "To Date", dataIndex: "PL_TO_DT" },
  { name: "Class", dataIndex: "CLASS" },
  { name: "Sub Class", dataIndex: "SUB_CLASS" },
  { name: "Product Name", dataIndex: "PRODUCT_NAME" },
  { name: "Cover Name", dataIndex: "COVER_NAME" },
  { name: "Agent", dataIndex: "AGENT" },
  { name: "Insured", dataIndex: "INSURED" },
  { name: "Status", dataIndex: "CM_STATUS" },
  { name: "Loss Cause", dataIndex: "CM_LOSS_CAUSE" },
  { name: "Policy Type", dataIndex: "POLICY_TYPE" },
  { name: "Reserve Amount", dataIndex: "RESERVE_AMNT" },
  { name: "Retention Amount", dataIndex: "RETENTION_AMNT" },
  { name: "1st Surp Amount", dataIndex: "SURP1_AMNT" },
  { name: "2nd Surp Amount", dataIndex: "SURP2_AMNT" },
  { name: "QS Amount", dataIndex: "QS_AMNT" },
  { name: "CQS Amount", dataIndex: "CQS_AMNT" },
  { name: "Facout Amount", dataIndex: "FACOUT_AMNT" },
  { name: "XOL Amount", dataIndex: "XOL_AMNT" },
  { name: "PL si", dataIndex: "PL_SI" },
  { name: "Retention Si", dataIndex: "RETENTION_SI" },
  { name: "1st Surp Si", dataIndex: "SURP1_SI" },
  { name: "2nd Surp Si", dataIndex: "SURP2_SI" },
  { name: "QS si", dataIndex: "QS_SI" },
  { name: "CQS Si", dataIndex: "CQS_SI" },
  { name: "Facout Si", dataIndex: "FACOUT_SI" },
  { name: "Treat Name", dataIndex: "TREATY_NAME" },
  { name: "Variant SI", dataIndex: "VAR_SI" },
  { name: "Variant Amount", dataIndex: "VAR_AMOUNT" },
];

export const RI_PREMIUM_COLUMNS = [
  { name: "Cession Month", dataIndex: "CESSION_MONTH" }, //
  { name: "Category Name", dataIndex: "BH_CATG_NAME" },
  { name: "Category Date", dataIndex: "BH_GL_DATE" },
  { name: "From Date", dataIndex: "BP_FM_DATE" },
  { name: "To Date", dataIndex: "BP_TO_DATE" },
  { name: "Year", dataIndex: "BP_UW_YR" },
  { name: "100% SI", dataIndex: "PERC_100_SI" },
  { name: "100% Prem", dataIndex: "PERC_100_PREM" },
  { name: "EML Prem", dataIndex: "EML_PREM" },
  { name: "Retention SI", dataIndex: "RETENTION_SI" },
  { name: "Retention Prem", dataIndex: "RETENTION_PREM" },
  { name: "QS SI", dataIndex: "QS_SI" },
  { name: "QS Prem", dataIndex: "QS_PREM" },
  { name: "QS COMM", dataIndex: "QS_COMM" },
  { name: "QS Prem Tax", dataIndex: "QS_PREMTAX" },
  { name: "CQS SI", dataIndex: "CQS_SI" },
  { name: "CQS Prem", dataIndex: "CQS_PREM" },
  { name: "CQS Comm", dataIndex: "CQS_COMM" },
  { name: "CQS Prem Tax", dataIndex: "CQS_PREMTAX" },
  { name: "1st Surp SI", dataIndex: "SURP1_SI" },
  { name: "1st Surp Prem", dataIndex: "SURP1_PREM" },
  { name: "1st Surp Comm", dataIndex: "SURP1_COMM" },
  { name: "1st Surp Prem Tax", dataIndex: "SURP1_PREMTAX" },
  { name: "2nd Surp SI", dataIndex: "SURP2_SI" },
  { name: "2nd Surp Prem", dataIndex: "SURP2_PREM" },
  { name: "2nd Surp Comm", dataIndex: "SURP2_COMM" },
  { name: "2nd Surp Prem Tax", dataIndex: "SURP2_PREMTAX" },
  { name: "Facout SI", dataIndex: "FACOUT_SI" },
  { name: "Facout Prem", dataIndex: "FACOUT_PREM" },
  { name: "Facout Comm", dataIndex: "FAC_COMM" },
  { name: "Facout Prem Tax", dataIndex: "FACOUT_PREMTAX" },
  { name: "Net Effect", dataIndex: "BH_NET_EFFECT" },
  { name: "Class", dataIndex: "CLASS" },
  { name: "Sub Class", dataIndex: "SUB_CLASS" },
  { name: "Status", dataIndex: "BH_STATUS" },
  { name: "Policy No", dataIndex: "BH_POL_NO" },
  { name: "Endorsement Number", dataIndex: "BH_POL_END_NO" },
  { name: "Broker Name", dataIndex: "BROKER_NAME" },
  { name: "Insured Name", dataIndex: "INSURED_NAME" },
  { name: "End Type", dataIndex: "PR_END_TYPE" },
];

/**
 *  {
           
           
        
            
          
         
        
           
         
            "SURP1_SI": 4000000,
            "SURP1_PREM": 200,
            "SURP1_COMM": 55,
            "SURP1_PREMTAX": 4,
            "SURP2_SI": 0,
            "SURP2_PREM": 0,
            "SURP2_COMM": 0,
            "SURP2_PREMTAX": 0,
            "FACOUT_SI": 0,
            "FACOUT_PREM": 0,
            "FAC_COMM": 0,
            "FACOUT_PREMTAX": 0,
            "BH_FACOUT_INDEX": null,
            "BH_POL_END_INDEX": 18,
            "BH_POL_INDEX": 46622,
            "BH_BATCH_NO": "514420",
            "BH_CR_INDEX": 524201,
            "CR_CV_CODE": "044",
            "CR_MC_CODE": "03",
            "BH_NET_EFFECT": "Debit",
            "BH_ORG_CODE": "50",
            "BH_OS_CODE": "01",
            "BH_PR_CODE": "031",
            "PR_PR_CODE_XX": "Fire Domestic Contents",
            "BH_PT_CODE": "MISC.TRTY.2024",
            "BH_RISK_INDEX": 526831,
            "CR_SC_CODE": "031",
            "BH_SS_CODE": "031",
            "CLASS": "FIRE DOMESTIC",
            "SUB_CLASS": "031 Domestic Contents",
            "BH_STATUS": "Completed",
            "BH_POL_NO": "1/01/031/0132/2007",
            "BH_POL_END_NO": "03/031/09843/2024",
            "BROKER_CODE": "A-AP01",
            "BROKER_NAME": "AP INSURANCE AGENCIES LTD.",
            "INSURED_CODE": "MR-0139",
            "INSURED_NAME": "MR. MAHENDRA K. SHAH & MRS. PRAGNA M.SHAH",
            "PR_END_ORDER": 4,
            "PR_END_TYPE": "Renewals",
            "CR_RISK_CATG": "0"
        },
 */
